# fly.toml app configuration file generated for fauxfriends on 2025-04-04T13:49:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fauxfriends'
primary_region = 'iad'

[build]
  dockerfile = 'src/main/docker/Dockerfile.jvm'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
